name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python numpy
      - name: Test script for errors
        run: |
          touch napaka.txt
      - name: Upload error file if exists and not empty
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: error-report
          path: napaka.txt

  run_tests:
    needs: setup_environment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: error-report
      - name: Check for error report
        run: |
          if [ -s napaka.txt ]; then
            echo "Napake so bile zaznane v prvem poslu."
            cat napaka.txt
            exit 1
          fi
      - name: Run tests
        run: python test_obdelave_slike.py

