name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies and check for errors
        run: |
          python -m pip install --upgrade pip && pip install opencv-python numpy 2> napaka.txt
      - name: Upload error file if exists and not empty
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: error-report
          path: napaka.txt

  run_tests:
    needs: setup_environment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/download-artifact@v4
        with:
          name: error-report
      - name: Check for error report
        run: |
          if [ -s napaka.txt ]; then
            echo "Napake so bile zaznane v prvem poslu."
            cat napaka.txt
            exit 1
          else
            echo "No errors found, proceeding to run tests."
      - name: Run tests
        run: python3 test_obdelave_slike.py
