name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python numpy
      - name: Run script and check for errors
        id: check_error
        run: |
          python naloga1.py > output.txt 2>&1
          if [ $? -ne 0 ]; then
            echo "ERROR" > napaka.txt
            echo "has_error=true" >> $GITHUB_ENV
          else
            echo "has_error=false" >> $GITHUB_ENV
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: error-report
          path: napaka.txt

  run_tests:
    needs: setup_environment
    if: env.has_error == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: error-report
      - name: Run tests
        run: |
          python test_obdelave_slike.py
